So far this has worked pretty well. Will cleanup later

diff --git a/bin/ldev b/bin/ldev
--- a/bin/ldev
+++ b/bin/ldev
@@ -2,59 +2,63 @@
 
 # cd "$NC_TRUNK_DEV_PATH/liferay-portal/"
 
-dir_path="$1"
-cmd="$2"
+# ==========
+dir_path="${1:-.}"
+cmd="${2:-all}"
 
-if [[ $dir_path != *"."* && $dir_path != *"/"* ]]; then
-	cmd="$dir_path"
-	dir_path=""
-fi
+liferay "$dir_path" "$cmd"
 
-if [[ -z $dir_path ]]; then
-	dir_path="$NC_TRUNK_PORTAL_PATH"
-else
-	tmp_dir_path="$(git rev-parse --show-toplevel 2>/dev/null)"
+# if [[ -z "$cmd" ]]; then
+# 	cmd="all"
+# fi
 
-	if [[ -n "$tmp_dir_path" ]]; then
-		dir_path="$tmp_dir_path"
-	fi
-fi
+# if [[ $dir_path != *"."* && $dir_path != *"/"* ]]; then
+# 	cmd="$dir_path"
+# 	dir_path=""
+# fi
 
-if [[ -z "$cmd" ]]; then
-	cmd="all"
-fi
+# if [[ -z $dir_path ]]; then
+# 	dir_path="$NC_TRUNK_PORTAL_PATH"
+# else
+# 	tmp_dir_path="$(git rev-parse --show-toplevel 2>/dev/null)"
+
+# 	if [[ -n "$tmp_dir_path" ]]; then
+# 		dir_path="$tmp_dir_path"
+# 	fi
+# fi
 
 
-if [[ -d "$dir_path" ]]; then
-	cd $dir_path
-	ant $cmd
+# if [[ -d "$dir_path" ]]; then
+# 	cd $dir_path
+# 	ant $cmd
 
-	if [[ $? = 0 ]]; then
-		# liferay dev
+# 	if [[ $? = 0 ]]; then
+# 		# liferay dev
 
-		if [[ -f "$dir_path/../startup.sh" ]]; then
-			$dir_path/../startup.sh
-		else
-			user_props="app.server.$USER.properties"
-			tomcat_path=""
+# 		if [[ -f "$dir_path/../startup.sh" ]]; then
+# 			$dir_path/../startup.sh
+# 		else
+# 			user_props="app.server.$USER.properties"
+# 			tomcat_path=""
 
-			if [[ -d "../tomcat" ]]; then
-				tomcat_path="../tomcat"
-			elif [[ -f "$user_props" ]]; then
-				tomcat_path=$(sed -n "s/^app\.server\.tomcat\.dir=\(.*\)/\1/ p" "$user_props")
-			fi
+# 			if [[ -d "../tomcat" ]]; then
+# 				tomcat_path="../tomcat"
+# 			elif [[ -f "$user_props" ]]; then
+# 				tomcat_path=$(sed -n "s/^app\.server\.tomcat\.dir=\(.*\)/\1/ p" "$user_props")
+# 			fi
 
-			if [[ -n "$tomcat_path" && -d "$tomcat_path" ]]; then
-				$tomcat_path/bin/catalina.sh run
-			else
-				echo "Could not find an app server to start"
-			fi
-		fi
-	fi
-else
-	echo "$dir_path is not a directory"
-fi
-
+# 			if [[ -n "$tomcat_path" && -d "$tomcat_path" ]]; then
+# 				$tomcat_path/bin/catalina.sh run
+# 			else
+# 				echo "Could not find an app server to start"
+# 			fi
+# 		fi
+# 	fi
+# else
+# 	echo "$dir_path is not a directory"
+# fi
+# ==========
+# 
 # if [[ -z $1 ]]; then
 # 	ant="all"
 # else
diff --git a/bin/liferay b/bin/liferay
--- a/bin/liferay
+++ b/bin/liferay
@@ -1,17 +1,70 @@
 #!/bin/sh
 
-base_path="${NC_TRUNK_DEV_PATH}"
+# base_path="${NC_TRUNK_DEV_PATH}"
 
-if [[ -n "$1" ]]; then
-	if [[ $1 == "60" ]]; then
-		base_path="${NC_BRANCHES_PATH}/6.0.x"
-	elif [[ $1 == "52" ]]; then
-		base_path="${NC_BRANCHES_PATH}/5.2.x"
-	elif [[ $1 == "maint" ]]; then
-		base_path="${NC_TRUNK_MAINT_PATH}"
+# if [[ -n "$1" ]]; then
+# 	if [[ $1 == "60" ]]; then
+# 		base_path="${NC_BRANCHES_PATH}/6.0.x"
+# 	elif [[ $1 == "52" ]]; then
+# 		base_path="${NC_BRANCHES_PATH}/5.2.x"
+# 	elif [[ $1 == "maint" ]]; then
+# 		base_path="${NC_TRUNK_MAINT_PATH}"
+# 	fi
+# fi
+
+# base_path="${base_path}/tomcat/bin/catalina.sh run"
+
+# $base_path
+
+# cd "$NC_TRUNK_DEV_PATH/liferay-portal/"
+
+dir_path="$1"
+cmd="$2"
+
+if [[ $dir_path != *"."* && $dir_path != *"/"* ]]; then
+	cmd="$dir_path"
+	dir_path=""
+fi
+
+if [[ -z $dir_path ]]; then
+	dir_path="$NC_TRUNK_PORTAL_PATH"
+else
+	tmp_dir_path="$(git rev-parse --show-toplevel 2>/dev/null)"
+
+	if [[ -n "$tmp_dir_path" ]]; then
+		dir_path="$tmp_dir_path"
 	fi
 fi
 
-base_path="${base_path}/tomcat/bin/catalina.sh run"
+if [[ -d "$dir_path" ]]; then
+	cd $dir_path
 
-$base_path
+	if [[ -n "$cmd" ]]; then
+		ant $cmd
+	fi
+
+	if [[ $? = 0 ]]; then
+		# liferay dev
+
+		if [[ -f "$dir_path/../startup.sh" ]]; then
+			$dir_path/../startup.sh
+		else
+			user_props="app.server.$USER.properties"
+			tomcat_path=""
+
+			if [[ -d "../tomcat" ]]; then
+				tomcat_path="../tomcat"
+			elif [[ -f "$user_props" ]]; then
+				tomcat_path=$(sed -n "s/^app\.server\.tomcat\.dir=\(.*\)/\1/ p" "$user_props")
+			fi
+
+			if [[ -n "$tomcat_path" && -d "$tomcat_path" ]]; then
+				$tomcat_path/bin/catalina.sh run
+			else
+				echo "Could not find an app server to start"
+			fi
+		fi
+	fi
+else
+	echo "$dir_path is not a directory"
+fi
